export const activities = [
  {
    label: "CeFiEx",
    count: 41917390,
    finding: ["blockchain.com"],
  },
  {
    label: "DeEx",
    count: 10526355,
    finding: ["1inch"],
  },
  {
    label: "CryptoTokens",
    count: 8479665,
    finding: ["gastoken.io"],
  },
  {
    label: "UniqueTokens",
    count: 5702590,
    finding: ["mct:", "xen", "batch", "mint", "nft"],
  },
  {
    label: "DecApps",
    count: 4862483,
    finding: ["unibright"],
  },
  {
    label: "FinDApps",
    count: 930960,
    finding: ["nexo"],
  },
  {
    label: "InteropBridges",
    count: 27476,
    finding: ["arbitrum", "axelar", "avalanche", "wormhole", "portal"],
  },
  {
    label: "MiscData",
    count: 4932,
    finding: [
      "phish",
      "hack",
      "fake_phishing3963",
      "heist",
      "fake_phishing3535",
      "fake_phishing3135",
      "fake_phishing4084",
      "fake_phishing4318",
      "high-risk",
    ],
  },
  {
    label: "NetOps",
    count: 425,
    finding: [
      "f2pool",
      "mining",
      "vitalik",
      "buterin",
      "baikalmine",
      "abyss",
      "finance",
      "nanopool",
      "stakefish",
      "baypool",
    ],
  },
  {
    label: "GameFi",
    count: 407,
    finding: [
      "axie",
      "infinity",
      "stepn",
      "ultimate",
      "champions",
      "gods",
      "unchained",
      "habbo",
      "crazydefenseheroes",
      "dustland",
      "gamee",
    ],
  },
];
