#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

pnpm run check-format ||
(
    echo '🤢 Bad formatting.
            Prettier Check Failed. Run "pnpm run format", add changes and try commit again.';
    false;
)

pnpm run check-lint ||
(
        echo '😤 ESLint Check Failed. 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

pnpm run check-types ||
(
    echo '🤡 Failed to check types.
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

echo '🏗️ Trying to build now.'

pnpm run build ||
(
    echo '❌👷 Build failed.
            Next build failed: View the errors above to see why. 
    '
    false;
)

echo '✅ Everything passed. You can commit now.'